version: '2'
services:
  go-server:
    image: gocd/gocd-server:v20.10.0
    ports:
      - "8153:8153"
    volumes:
      - ./godata:/godata
      - ./cruise-config.xml:/godata/config/cruise-config.xml
      - ./.ssh:/home/go/.ssh
    environment:
      GOCD_PLUGIN_INSTALL_docker-registry-artifact-plugin: https://github.com/gocd/docker-registry-artifact-plugin/releases/download/v1.3.0-136-exp/docker-registry-artifact-plugin-1.3.0-136.jar
      GOCD_PLUGIN_INSTALL_gocd-aws-based-secrets-plugin: https://github.com/gocd/gocd-aws-based-secrets-plugin/releases/download/v1.1.0-61-exp/gocd-aws-based-secrets-plugin-1.1.0-61.jar
      GOCD_PLUGIN_INSTALL_gocd-slack-task: https://github.com/Vincit/gocd-slack-task/releases/download/v2.0/gocd-slack-task-2.0.jar
  go-agent1:
    image: gocd/gocd-agent-alpine-3.10:v20.10.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    volumes:
      - ./.ssh:/home/go/.ssh
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: http://go-server:8153/go
  go-agent2:
    image: gocd/gocd-agent-alpine-3.10:v20.10.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    volumes:
      - ./.ssh:/home/go/.ssh
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: http://go-server:8153/go
